### ISSUE TITLE
MOC.from_polygon(): pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by ajstewart** [cds-astro/mocpy#57]
I seem to be having a wrap issue making polygons for areas of the sky around a Dec of +00.

For example I try to make the following MOC using sky coords shown in this plot (the skycoords make up the blue points around the border):

<img width="460" alt="Screen Shot 2020-06-25 at 19 03 41" src="https://user-images.githubusercontent.com/3306161/85691217-a5ae0f00-b717-11ea-931c-c5b69efa1114.png">

it errors with the output below.

I have other fields like this one and they all run fine apart from the ones at +00 dec, failures:

* 0918+00
* 1147+00
* 2004+00

```
Python 3.7.4
MOCPy              0.8.3
cdshealpix         0.5.2
```

```
 moc = MOC.from_polygon_skycoord(coords, max_depth=9)

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/git/checkouts/cds-healpix-rust-1e389e7afcf43397/36c794c/src/special_points_finder.rs:209:13
stack backtrace:
   0:     0x7f6ba303d8b5 - backtrace::backtrace::libunwind::trace::h934f9000aebd3cdb
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7f6ba303d8b5 - backtrace::backtrace::trace_unsynchronized::hcd6e39da2d76d8d6
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7f6ba303d8b5 - std::sys_common::backtrace::_print_fmt::ha0ad3a34f556be49
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7f6ba303d8b5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8b081861d17846db
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7f6ba305baec - core::fmt::write::hdf236390fbd68d3d
                               at src/libcore/fmt/mod.rs:1076
   5:     0x7f6ba303bcf3 - std::io::Write::write_fmt::h5bb44e52de2a261a
                               at src/libstd/io/mod.rs:1537
   6:     0x7f6ba303fe70 - std::sys_common::backtrace::_print::ha4c1f300ce7771d8
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7f6ba303fe70 - std::sys_common::backtrace::print::h91852b42a347b2e6
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f6ba303fe70 - std::panicking::default_hook::{{closure}}::h2fe76e4c26a76fb6
                               at src/libstd/panicking.rs:198
   9:     0x7f6ba303fbbc - std::panicking::default_hook::h2c17754d359ee45d
                               at src/libstd/panicking.rs:218
  10:     0x7f6ba30404a7 - std::panicking::rust_panic_with_hook::h57453d1f9e90d130
                               at src/libstd/panicking.rs:486
  11:     0x7f6ba30400ab - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:     0x7f6ba305aef1 - core::panicking::panic_fmt::hd101a87121fa411f
                               at src/libcore/panicking.rs:101
  13:     0x7f6ba305ae3d - core::panicking::panic::h02171c407fa1462f
                               at src/libcore/panicking.rs:56
  14:     0x7f6ba301d403 - cdshealpix::special_points_finder::arc_special_point_in_eqr::hc448bce441fb7041
  15:     0x7f6ba301c8ed - cdshealpix::special_points_finder::arc_special_points::h9a311b3a3832ca4a
  16:     0x7f6ba3015609 - cdshealpix::nested::Layer::polygon_coverage::hae121018a24f79a7
  17:     0x7f6ba2ff4f4a - cdshealpix::cdshealpix::polygon_search::h794c282a6e21fcb1
  18:     0x7f6ba2febd87 - cdshealpix::cdshealpix::__pyo3_get_function_polygon_search::__wrap::{{closure}}::h1c96c6609f1202f1
  19:     0x7f6ba2ff4924 - cdshealpix::cdshealpix::__pyo3_get_function_polygon_search::__wrap::h1e16695d5bbf4113
  20:     0x558a90875744 - _PyMethodDef_RawFastCallKeywords
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:694
  21:     0x558a90875861 - _PyCFunction_FastCallKeywords
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:734
  22:     0x558a908e12bd - call_function
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4568
  23:     0x558a908e12bd - _PyEval_EvalFrameDefault
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3093
  24:     0x558a90825539 - _PyEval_EvalCodeWithName
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3930
  25:     0x558a90874ef5 - _PyFunction_FastCallKeywords
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:433
  26:     0x558a908e0f29 - call_function
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4616
  27:     0x558a908e0f29 - _PyEval_EvalFrameDefault
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3093
  28:     0x558a90825539 - _PyEval_EvalCodeWithName
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3930
  29:     0x558a90874f57 - _PyFunction_FastCallKeywords
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:433
  30:     0x558a908dd8cc - call_function
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4616
  31:     0x558a908dd8cc - _PyEval_EvalFrameDefault
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3139
  32:     0x558a90825539 - _PyEval_EvalCodeWithName
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3930
  33:     0x558a90874f57 - _PyFunction_FastCallKeywords
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:433
  34:     0x558a908dd8cc - call_function
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4616
  35:     0x558a908dd8cc - _PyEval_EvalFrameDefault
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3139
  36:     0x558a90874ccb - function_code_fastcall
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:283
  37:     0x558a90874ccb - _PyFunction_FastCallKeywords
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:408
  38:     0x558a908dc806 - call_function
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4616
  39:     0x558a908dc806 - _PyEval_EvalFrameDefault
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3124
  40:     0x558a90825539 - _PyEval_EvalCodeWithName
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3930
  41:     0x558a90826424 - PyEval_EvalCodeEx
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3959
  42:     0x558a9082644c - PyEval_EvalCode
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:524
  43:     0x558a9093bb74 - run_mod
                               at /tmp/build/80754af9/python_1565725737370/work/Python/pythonrun.c:1035
  44:     0x558a90945eb1 - PyRun_FileExFlags
                               at /tmp/build/80754af9/python_1565725737370/work/Python/pythonrun.c:988
  45:     0x558a909460a3 - PyRun_SimpleFileExFlags
                               at /tmp/build/80754af9/python_1565725737370/work/Python/pythonrun.c:429
  46:     0x558a90947195 - pymain_run_file
                               at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:433
  47:     0x558a90947195 - pymain_run_filename
                               at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:1612
  48:     0x558a90947195 - pymain_run_python
                               at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:2873
  49:     0x558a90947195 - pymain_main
                               at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:3413
  50:     0x558a909472bc - _Py_UnixMain
                               at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:3448
  51:     0x7f6bee483545 - __libc_start_main
  52:     0x558a908ec062 - <unknown>
                               at ../sysdeps/x86_64/elf/start.S:103
Traceback (most recent call last):
  File "gen_mocs.py", line 69, in <module>
    themoc = gen_moc(f)
  File "gen_mocs.py", line 51, in gen_moc
    moc = MOC.from_polygon_skycoord(coords, max_depth=9)
  File "/suphys/aste7152/.conda/envs/astropy3/lib/python3.7/site-packages/mocpy/moc/moc.py", line 688, in from_polygon_skycoord
    return MOC.from_polygon(lon=skycoord.icrs.ra, lat=skycoord.icrs.dec, max_depth=max_depth)
  File "/suphys/aste7152/.conda/envs/astropy3/lib/python3.7/site-packages/mocpy/moc/moc.py", line 714, in from_polygon
    pix, depth, fully_covered_flags = cdshealpix.polygon_search(lon, lat, max_depth)
  File "/suphys/aste7152/.conda/envs/astropy3/lib/python3.7/site-packages/cdshealpix/nested/healpix.py", line 582, in polygon_search
    ipix, depth, full = cdshealpix.polygon_search(depth, lon, lat, flat)
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

**Comment by fxpineau** [comment]
@bmatthieu3 (cc. @ajstewart ) this bug has been fixed in the [rust code](https://github.com/cds-astro/cds-healpix-rust/commit/a08f9f41687ac08b3c0c13e0ebde9501b7d470f2) 3 days ago. FYI I also pushed v0.5.2 on [crates.io](https://crates.io/crates/cdshealpix).

**Comment by ajstewart** [comment]
Hi, do you have an idea of when this could be fixed? I'd like to use mocpy but have had to hold off for now, so just wondering if I should plan to not use it long term. Thanks!

**Comment by bmatthieu3** [comment]
Hi @ajstewart,

I updated mocpy's version to 0.8.4 following the correction from @fxpineau. Can you update the package and tell me if it works on your side now ?

**Comment by ajstewart** [comment]
Unfortunately after upgrading to 0.8.4 I'm still getting the same error on the same field as I originally posted. Just to remind this is getting all the pix2world values of the outline of the FITS image above and then using these with `from_polygon`. I can attempt to provide any other information you need.

```
import mocpy
mocpy.__version__
'0.8.4'
```

```
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-10-b65b135ee68d> in <module>
----> 1 moc = MOC.from_polygon(coords[:,0] * u.deg, coords[:,1] * u.deg, max_depth=9)

~/.conda/envs/astropy3/lib/python3.7/site-packages/mocpy/moc/moc.py in from_polygon(cls, lon, lat, max_depth)
    712             The resulting MOC
    713         """
--> 714         pix, depth, fully_covered_flags = cdshealpix.polygon_search(lon, lat, max_depth)
    715         return MOC.from_healpix_cells(pix, depth, fully_covered_flags)
    716 

~/.conda/envs/astropy3/lib/python3.7/site-packages/cdshealpix/nested/healpix.py in polygon_search(lon, lat, depth, flat)
    580         raise IndexError("There must be at least 3 distinct vertices in order to form a polygon")
    581 
--> 582     ipix, depth, full = cdshealpix.polygon_search(depth, lon, lat, flat)
    583 
    584     return ipix, depth, full

PanicException: called `Option::unwrap()` on a `None` value
```

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/git/checkouts/cds-healpix-rust-1e389e7afcf43397/36c794c/src/special_points_finder.rs:209:13
stack backtrace:
   0:     0x7f9e0c6818b5 - backtrace::backtrace::libunwind::trace::h934f9000aebd3cdb
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7f9e0c6818b5 - backtrace::backtrace::trace_unsynchronized::hcd6e39da2d76d8d6
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7f9e0c6818b5 - std::sys_common::backtrace::_print_fmt::ha0ad3a34f556be49
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7f9e0c6818b5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8b081861d17846db
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7f9e0c69faec - core::fmt::write::hdf236390fbd68d3d
                               at src/libcore/fmt/mod.rs:1076
   5:     0x7f9e0c67fcf3 - std::io::Write::write_fmt::h5bb44e52de2a261a
                               at src/libstd/io/mod.rs:1537
   6:     0x7f9e0c683e70 - std::sys_common::backtrace::_print::ha4c1f300ce7771d8
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7f9e0c683e70 - std::sys_common::backtrace::print::h91852b42a347b2e6
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f9e0c683e70 - std::panicking::default_hook::{{closure}}::h2fe76e4c26a76fb6
                               at src/libstd/panicking.rs:198
   9:     0x7f9e0c683bbc - std::panicking::default_hook::h2c17754d359ee45d
                               at src/libstd/panicking.rs:218
  10:     0x7f9e0c6844a7 - std::panicking::rust_panic_with_hook::h57453d1f9e90d130
                               at src/libstd/panicking.rs:486
  11:     0x7f9e0c6840ab - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:     0x7f9e0c69eef1 - core::panicking::panic_fmt::hd101a87121fa411f
                               at src/libcore/panicking.rs:101
  13:     0x7f9e0c69ee3d - core::panicking::panic::h02171c407fa1462f
                               at src/libcore/panicking.rs:56
  14:     0x7f9e0c661403 - cdshealpix::special_points_finder::arc_special_point_in_eqr::hc448bce441fb7041
  15:     0x7f9e0c6608ed - cdshealpix::special_points_finder::arc_special_points::h9a311b3a3832ca4a
  16:     0x7f9e0c659609 - cdshealpix::nested::Layer::polygon_coverage::hae121018a24f79a7
  17:     0x7f9e0c638f4a - cdshealpix::cdshealpix::polygon_search::h794c282a6e21fcb1
  18:     0x7f9e0c62fd87 - cdshealpix::cdshealpix::__pyo3_get_function_polygon_search::__wrap::{{closure}}::h1c96c6609f1202f1
  19:     0x7f9e0c638924 - cdshealpix::cdshealpix::__pyo3_get_function_polygon_search::__wrap::h1e16695d5bbf4113
  20:     0x5573671fd744 - _PyMethodDef_RawFastCallKeywords
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:694
  21:     0x5573671fd861 - _PyCFunction_FastCallKeywords
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:734
  22:     0x5573672692bd - call_function
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4568
  23:     0x5573672692bd - _PyEval_EvalFrameDefault
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3093
  24:     0x5573671ad539 - _PyEval_EvalCodeWithName
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3930
  25:     0x5573671fcef5 - _PyFunction_FastCallKeywords
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:433
  26:     0x557367268f29 - call_function
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4616
  27:     0x557367268f29 - _PyEval_EvalFrameDefault
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3093
  28:     0x5573671ad539 - _PyEval_EvalCodeWithName
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3930
  29:     0x5573671fcf57 - _PyFunction_FastCallKeywords
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:433
  30:     0x5573672658cc - call_function
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4616
  31:     0x5573672658cc - _PyEval_EvalFrameDefault
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3139
  32:     0x5573671ad539 - _PyEval_EvalCodeWithName
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3930
  33:     0x5573671fcf57 - _PyFunction_FastCallKeywords
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:433
  34:     0x5573672658cc - call_function
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4616
  35:     0x5573672658cc - _PyEval_EvalFrameDefault
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3139
  36:     0x5573671fcccb - function_code_fastcall
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:283
  37:     0x5573671fcccb - _PyFunction_FastCallKeywords
                               at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:408
  38:     0x557367264806 - call_function
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4616
  39:     0x557367264806 - _PyEval_EvalFrameDefault
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3124
  40:     0x5573671ad539 - _PyEval_EvalCodeWithName
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3930
  41:     0x5573671ae424 - PyEval_EvalCodeEx
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3959
  42:     0x5573671ae44c - PyEval_EvalCode
                               at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:524
  43:     0x5573672c3b74 - run_mod
                               at /tmp/build/80754af9/python_1565725737370/work/Python/pythonrun.c:1035
  44:     0x5573672cdeb1 - PyRun_FileExFlags
                               at /tmp/build/80754af9/python_1565725737370/work/Python/pythonrun.c:988
  45:     0x5573672ce0a3 - PyRun_SimpleFileExFlags
                               at /tmp/build/80754af9/python_1565725737370/work/Python/pythonrun.c:429
  46:     0x5573672cf195 - pymain_run_file
                               at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:433
  47:     0x5573672cf195 - pymain_run_filename
                               at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:1612
  48:     0x5573672cf195 - pymain_run_python
                               at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:2873
  49:     0x5573672cf195 - pymain_main
                               at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:3413
  50:     0x5573672cf2bc - _Py_UnixMain
                               at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:3448
  51:     0x7f9e57adf555 - __libc_start_main
  52:     0x557367274062 - <unknown>
                               at ../sysdeps/x86_64/elf/start.S:103
```

**Comment by bmatthieu3** [comment]
What are the polygon vertex coordinates you are using? I will create a new test in mocpy with this input

**Comment by ajstewart** [comment]
Here's the array I'm using: https://www.dropbox.com/s/5o0as54di1gtqfe/moc_coords.npy?dl=0

For which I try ```moc = MOC.from_polygon(coords[:,0] * u.deg, coords[:,1] * u.deg, max_depth=9)```

**Comment by bmatthieu3** [comment]
mocpy relies on the cdshealpix python package (which is a wrapper around the rust library of the same name). When calling from_polygon it actually calls internally the polygon_search method from cdshealpix. So I released a new version of cdshealpix that should take into account the fix on the rust library. Can you do a `pip install -U cdshealpix` and retry ? You should have the 0.5.3 version of cdshealpix

**Comment by ajstewart** [comment]
I wondered that when I saw the error message was still referencing it.

Thanks for updating `cdshealpix`, I've tried 0.5.3 and can confirm I no longer have this error in using `from_ploygon`.
